"""add autoincrement to order

Revision ID: 0ce3c599ec56
Revises: 32eb11a6589e
Create Date: 2023-09-12 12:24:41.471406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ce3c599ec56"
down_revision: Union[str, None] = "32eb11a6589e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
