"""Create role and order

Revision ID: 32eb11a6589e
Revises: 870f012a9693
Create Date: 2023-09-10 23:02:01.747890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32eb11a6589e'
down_revision: Union[str, None] = '870f012a9693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('item', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('item', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('role', sa.Column('permission', sa.String(), nullable=True))
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('role', 'permission')
    op.alter_column('item', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
