"""fix user

Revision ID: 71cfe8d64739
Revises: c99e640bfb28
Create Date: 2023-09-15 16:55:13.761178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71cfe8d64739"
down_revision: Union[str, None] = "c99e640bfb28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###
